<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MemberTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         DB::table('users')->insert([
             array('name'=>'Cong NV','email'=>'congnv@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>1,'grade_id'=>1,'url_avt'=>'mr cong.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
             array('name'=>'Binh DC','email'=>'binhdc@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>3,'url_avt'=>'mr Binh.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
              array('name'=>'Dung','email'=>'dung@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Dung.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
              array('name'=>'Hai Gemini','email'=>'gemini.wind285@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Hai.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
              array('name'=>'Nam Kominam','email'=>'kominam2511@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Nam.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
              array('name'=>'Nhan','email'=>'nhan@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Nhan.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
               array('name'=>'Quan','email'=>'quan@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Quan.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Anh Uno','email'=>'rubik.hanu@gmail.com','gender'=>2,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mrs Anh.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Huyen','email'=>'huyen@gmail.com','gender'=>2,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mrs Huyen.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Phuong','email'=>'phuong@gmail.com','gender'=>2,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mrs Phuong.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Thanh ','email'=>'thanh@gmail.com','gender'=>1,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'mr Thanh.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Thao ','email'=>'thao@gmail.com','gender'=>2,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>2,'grade_id'=>4,'url_avt'=>'ms Thao.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
                array('name'=>'Thuong ','email'=>'thuong@gmail.com','gender'=>2,'password' =>bcrypt('123456'),'bio'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh adipiscing sit amet. In eu justo a felis faucibus ornare vel id metus. Vestibulum ante ipsum primis in faucibus.','url_fb'=>'#','url_gmail'=>'#','url_github'=>'#','position_id'=>3,'grade_id'=>4,'url_avt'=>'ms Thuong.jpg', 'created_at' => Carbon::now(),'updated_at' => Carbon::now()),
        ]);
    }
}
